### ISSUE TITLE
Improving ftp progress status.  Would be nice to show number of file send over total.

### ISSUE THREAD

**Issue by ldl5007** [dkelosky/js-osFtp#17]

**Comment by dkelosky** [comment]
That's a good idea

**Comment by ldl5007** [comment]
You a good idea

On Wed, Nov 4, 2015 at 5:05 PM, dkelosky notifications@github.com wrote:

> That's a good idea
> On Nov 4, 2015 3:39 PM, "ldl5007" notifications@github.com wrote:
> 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/dkelosky/js-osFtp/issues/17.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dkelosky/js-osFtp/issues/17#issuecomment-153883711.

## 

Lam Ly
ldl5007@gmail.com
412-478-6389

**Comment by dkelosky** [comment]
This is logged as an enhancement, not a bug.  Otherwise, things are working as designed.
