### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by dkelosky** [dkelosky/js-osFtp#34]
The line number was tree.js:77 
TreeNode.addRelativePath(node-v4.2.1/test/fixtures/keys/0-dns-cert.pem)

**Comment by dkelosky** [comment]
I cant test the tree render because this still happens!

**Comment by ldl5007** [comment]
This happen when one of the folder name is 'keys' and all javascripts object have keys method built in so this resulted in retreiving the keys object method.  Which caused the problem.

Fixed by reverse back to use array instead of object for node Array.
